### ISSUE TITLE
Zooming reverts tickFormat to defaults

### ISSUE THREAD

**Issue by carpiediem** [marmelab/EventDrops#198]
I built a chart with a custom tickFormat, but when I zoom, the values all change (e.g. 0:00:01 to 12:00:01).

```
var eventDropsChart = d3.chart.eventDrops()
        .tickFormat(d3.timeFormat("%H:%M:%S"))
```

I'm trying to find a temporary solution by setting the format in zoomend, but it's not working so far...

**Comment by jpetitcolas** [comment]
This issue is related to the format expected by `tickFormat` parameter (it should be a function from memory).

The good news is: we changed the way we handled the tick formats in last version (`1.x.x`). I would recommend you to update your EventDrops version using [our migration guide](https://github.com/marmelab/EventDrops/blob/master/MIGRATION-1.0.md).

To tune tick format, you just have to specify strings according to the zoomed time. For instance, displaying your custom format for hours, minutes and seconds can be done via the following:

``` js
const chart = eventDrops({
    axis: {
        formats: {
            milliseconds: '%L',
            seconds: '%H:%M:%S',
            minutes: '%H:%M:%S',
            hours: '%H:%M:%S',
            days: '%a %d',
            weeks: '%b %d',
            months: '%B',
            year: '%Y',
        }
    }
});
```

It gives you the following result, using the demo as support:

![sample](https://user-images.githubusercontent.com/688373/35987057-09c4dbd2-0cfb-11e8-9bf8-56c555b01719.gif)

**Comment by carpiediem** [comment]
Thanks for the update.

The migration guide would be useful on the project home page.  As is, some parts of the configuration guide is pretty hard to understand.  Since every heading is an h3 element, it's not clear which should be attributes of the config object and which should be sub-attributes.  The sections that include examples are much more clear.

**Comment by jpetitcolas** [comment]
Indeed, documentation looks really bad. Thanks for the report. We are going to fix that shortly. :)
