### ISSUE TITLE
Some data are outside the SVG viewport

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/EventDrops#96]
For instance, currently:

![image](https://cloud.githubusercontent.com/assets/688373/18227399/288b6afa-7223-11e6-8f77-5f02afe35439.png)

If we put another CSS rule on the SVG element (`overflow: visible;`), we have the correct view:

![image](https://cloud.githubusercontent.com/assets/688373/18227404/5877be26-7223-11e6-8e38-7c23a38fee78.png)

SVG has a red background on the second screenshot.

We need to draw data visible in the viewport, and only them.

**Comment by susanweber** [comment]
If this is the same bug I have observed, it appears related to the width of the area reserved for labels. You might just be missing a ( - labelWidth) somewhere.  I am attaching a short example showing a workaround, which is to suppress label display entirely
[eventDrop.html.txt](https://github.com/marmelab/EventDrops/files/504712/eventDrop.html.txt)

**Comment by bmasch** [comment]
I have found that if the chart is place within a DOM element with a restricted width (a page in an IFRAME, in my case), the eventDrops svg IS sized appropriately to fit inside that element, whereas the g.chart-wrapper element within is NOT. 

It seems that the maximum for d3.scale.range is not set correctly as not only are circles rendered outside the svg area, but also the axis ticks.

Using the axis.Format function, the axis.scale.range can be retrieved. As an example, if the svg width is 1000px, the range thus retrieved is [0,1000]. It actually should be 1000 minus the offset due to the width of the labels container on the left.

I tried just setting it to what it should be (with a function passed to axisFormat), but it only changes the range in time to rescale the axis itself, not the placement of the circles etc. Sad.
